services:
  mlflow:
    image: dhi.io/mlflow:3
    container_name: mlflow_container
    ports:
      - "5001:5001"
    volumes:
      - ./service-mounts/mlruns:/mlruns
    command: >
      server  --host 0.0.0.0  --port 5001  --backend-store-uri /mlruns  --default-artifact-root /mlruns
  prometheus:
    image: prom/prometheus:v3
    container_name: prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - ./service-mounts/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    
  grafana:
    image: grafana/grafana:11.6
    container_name: grafana_container
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
  mlruns:
  prometheus-data:

