global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "eep"
    static_configs:
      - targets: ["eep:8080"]
    metrics_path: /metrics

  - job_name: "iep1-inference"
    static_configs:
      - targets: ["iep1-inference:8000"]
    metrics_path: /metrics

  - job_name: "iep2-calibration"
    static_configs:
      - targets: ["iep2-calibration:8001"]
    metrics_path: /metrics
